name: Node.js CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
          scope: '@madelavega'
      - run: npm test
      - run: npm run bundle
      - if: github.ref == 'refs/heads/develop'
        run: npm run next-ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: github.ref == 'refs/heads/master'
        run: npm run latest-ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
