name: Build & publish delavega-lib

on:
  push:
    branches:
      - master
      - develop

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      -uses: ridedott/merge-me-action@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
          scope: '@madelavega'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci
      - run: npm test
      - run: npm run bundle
      - if: github.ref == 'refs/heads/develop'
        run: npm run next-ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: github.ref == 'refs/heads/master'

        run: npm run latest-ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}